version: 2
jobs:
  run_tests:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 25
  build_image:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Building"
      - run: sleep 15
  deploy:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "ship! ship! ship!"
      - run: sleep 15
workflows:
  version: 2
  one_and_two:
    jobs:
      - run_tests
      - build_image
          requires:
            - run_tests
      - deploy
          requires:
            - build_image
